<?php
/**
 * Stagebit
 * Stagebit Signup Form
 *
 * @category   Stagebit
 * @package    Stagebit_Signup
 * @copyright  Copyright © 2020 Stagebit 
 * @license    
 */

$formActionUrl = $block->geActionUrl();
?>
<form class="form signup" action="<?= /* @noEscape */ $formActionUrl ?>" title="Signup" id="signup-form" method="post" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml($block->getData('cc_title')) ?></span></legend><br />
        <div class="field note no-label"><?= $block->escapeHtml($block->getData('cc_content')) ?></div>
        <div class="field name required">
            <label class="label" for="c_name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="c_name" id="c_name" title="<?= $block->escapeHtml(__('Name')) ?>" class="input-text" type="text" data-validate="{required:true, 'validate-alphanum-with-spaces' : true, 'validate-no-html-tags' : true}"/>
            </div>
        </div>

        <div class="field email required">
            <label class="label" for="c_email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="c_email" id="c_email" title="<?= $block->escapeHtml(__('Email')) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>

        <div class="field c_password required">
            <label class="label" for="c_password"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
            <div class="control">
                <input name="c_password" id="c_password" title="<?= $block->escapeHtml(__('Password')) ?>" value="" class="input-text" type="password" data-validate="{required:true, 'validate-password' : true}"/>
            </div>
        </div>
        
        <div class="field telephone required">
            <label class="label" for="c_telephone"><span><?= $block->escapeHtml(__('Telephone No.')) ?></span></label>
            <div class="control">
                <input name="c_telephone" id="c_telephone" title="<?= $block->escapeHtml(__('Telephone No.')) ?>" value="" class="input-text" type="text" data-validate="{required:true, 'validate-digits' : true}"/>
            </div>
        </div>

        <div class="field birthdate">
            <label class="label" for="c_bdate"><span><?= $block->escapeHtml(__('Birth Date')) ?></span></label>
            <div class="control">
                <input name="c_bdate" id="c_bdate" title="<?= $block->escapeHtml(__('Birth Date')) ?>" class="input-text" type="date" data-validate="{required:false, 'validate-date' : true}"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtml(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>